[package]
name = "maller"
description="a rust library crate that calls closures depending on the input data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

